remote_theme: "jekyll/minima@c6e74bb"
google_analytics: UA-NNNNNNNN-N // Google Analyticsの有効化のために仮の値を設定
author: User
email: your-email@domain.com
lang: ja
twitter:
  card: summary_large_image
  username: @user